Sg/endpoints
tilangapramithvidusara/RFP_AI_PCF pull request #1
Opened 2024-04-04 10:49 UTC by sankethgunasekara

Have added the Endpoints for the Input requirement request and have Retrieve the data and showed in the Table

2024-04-04 11:15 UTC, tilangapramithvidusara requested changes

2024-04-04 11:15 UTC, tilangapramithvidusara commented on RFPAIPCF/src/App.tsx
change this class component as functional component

2024-04-04 11:15 UTC, tilangapramithvidusara commented on RFPAIPCF/src/components/Table.tsx
> +interface TableProps {
move this interfaces into common types file

2024-04-04 11:15 UTC, tilangapramithvidusara commented on RFPAIPCF/src/components/Table.tsx
> +            <th>REQUIREMENTS</th>
Get this hard coded view Text from language json

2024-04-04 11:15 UTC, tilangapramithvidusara commented on RFPAIPCF/src/components/Table.tsx
> +              <td>{row.requirement}</td>
use ? operator

2024-04-04 11:15 UTC, tilangapramithvidusara commented on RFPAIPCF/src/components/Table.tsx
> +        title="Enter Your Text"
get from language json

2024-04-04 11:15 UTC, tilangapramithvidusara commented on RFPAIPCF/src/components/Table.tsx
> +          placeholder="Enter Your Text Here..."
get from language json

2024-04-04 11:15 UTC, tilangapramithvidusara commented on RFPAIPCF/src/pages/UserInput.tsx
> +          message.error("Invalid response format");
get from language json

2024-04-05 02:26 UTC, sankethgunasekara commented
I have done the requested changes

2024-04-05 03:43 UTC, tilangapramithvidusara approved these changes

2024-04-05 03:43 UTC, merged